### ISSUE TITLE
Add feedback & licence

### ISSUE THREAD

**Issue by Zarpoosh** [echoWebNerds/VsCode_Front-End#2]
<Add the section of feedback >
Have a question? Start a discussion on [GitHub Discussions](https://github.com/redhat-developer/vscode-java/discussions),
File a bug in [GitHub Issues](https://github.com/redhat-developer/vscode-java/issues),
Chat with us on [Gitter](https://gitter.im/redhat-developer/vscode-java),
[Tweet us](https://twitter.com/VSCodeJava/) with other feedback.

License
EPL 2.0, See [LICENSE] for more information.

**Comment by echoWebNerds** [comment]
https://github.com/echoWebNerds/VsCode_Front-End/issues
